# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  push:
    branches:
    - release/*
    paths-ignore:
    - '**/README.md'
    - '**/docs'
    - '.github/**'
    - "docs/**"
    - ".git/*"
    - ".vs/*"
    - ".config/*"
    - ".github/*"
    - "Directory.Build.props"
    - "Directory.Build.targets"
    - "Directory.Build.props"
    - "docker-compose.yml"
    - "docker-compose.override.yml"
    - "docker-compose.vs.debug.yml"
    - "docker-compose.vs.release.yml"
    - "docker-compose.dcrpoj"
    - "**/*.sln"
    - "global.json"
    - "LICENSCE"
    - "Nuget.config"
    - "SECURITY.md"
    - "SPONSORS.md"
    - "README.md"
    - "samples"
    - "nuget"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-latest, ubuntu-latest, windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v3
      with:        
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x


    - uses: dotnet/nbgv@master
      id: nbgv
 
    - name: Display Package Version
      run: echo "PackageVersion=${{ steps.nbgv.outputs.SemVer2 }}"

    - name: Restore dependencies
      run: dotnet restore src/TechAdvisor.AuditLogging.sln
    - name: Build
      run: dotnet build src/TechAdvisor.AuditLogging.sln --configuration Release --no-restore -p:Version=${{ steps.nbgv.outputs.SemVer2 }}

    - name: Push
      if: ${{ (github.event_name == 'push') && (runner.os == 'Windows') }} 
      run: dotnet nuget push .\nuget\*.nupkg  --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

